name: docker-build
description: Reusable action to build repos' docker images

runs:
  using: composite
  steps:
    - name: ci/prepare-docker-environment
      uses: ./.github/actions/docker-prepare

    - name: cd/scan-docker-security
      uses: anchore/scan-action@7037fa011853d5a11690026fb85feee79f4c946c # v7.3.2
      with:
        image: "mattermost/atlantis"
        output-format: table
        only-fixed: true
        fail-build: false
        severity-cutoff: critical

    - name: cd/push-image-pr
      run: "make push-image-pr"
      shell: bash
      if: github.event_name == 'pull_request'

    - name: Set TAG variable if a tag is pushed
      run: echo "TAG=${GITHUB_REF#refs/tags/}" >> $GITHUB_ENV
      shell: bash
      if: startsWith(github.ref, 'refs/tags/')

    - name: cd/push-image-with-tag
      run: "make push-image TAG=${TAG}"
      shell: bash
      if: startsWith(github.ref, 'refs/tags/')

    - name: cd/push-image
      run: "make push-image"
      shell: bash
      if: github.event_name != 'pull_request' && !startsWith(github.ref, 'refs/tags/')
