name: docker-build
description: Reusable action to build repos' docker images

runs:
  using: composite
  steps:
    - name: ci/prepare-docker-environment
      uses: ./.github/actions/docker-prepare

    - name: cd/scan-docker-security
      uses: aquasecurity/trivy-action@062f2592684a31eb3aa050cc61e7ca1451cecd3d # v0.18.0
      with:
        image-ref: "mattermost/atlantis"
        format: "table"
        ignore-unfixed: true
        vuln-type: "os,library"
        severity: "CRITICAL"

    - name: cd/push-image-pr
      run: "make push-image-pr"
      shell: bash
      if: github.event_name == 'pull_request'

    - name: Set TAG variable if a tag is pushed
      run: echo "TAG=${GITHUB_REF#refs/tags/}" >> $GITHUB_ENV
      shell: bash
      if: startsWith(github.ref, 'refs/tags/')

    - name: cd/push-image-with-tag
      run: "make push-image TAG=${TAG}"
      shell: bash
      if: startsWith(github.ref, 'refs/tags/')

    - name: cd/push-image
      run: "make push-image"
      shell: bash
      if: github.event_name != 'pull_request' && !startsWith(github.ref, 'refs/tags/')
